name: cargo-checkmate phases

on:
  workflow_call:
    inputs:
      checkmate-version:
        type: string
        default: "^0.1.14"

jobs:
  audit:
    uses: ./.github/workflows/callee-phase.yaml
    with:
      phase: audit

  build:
    uses: ./.github/workflows/callee-phase.yaml
    with:
      phase: build

  check:
    uses: ./.github/workflows/callee-phase.yaml
    with:
      phase: check

  clippy:
    uses: ./.github/workflows/callee-phase.yaml
    with:
      phase: clippy

  doc:
    uses: ./.github/workflows/callee-phase.yaml
    with:
      phase: doc

  format:
    uses: ./.github/workflows/callee-phase.yaml
    with:
      phase: format

  test:
    uses: ./.github/workflows/callee-phase.yaml
    with:
      phase: test

