name: cargo-checkmate phases

on: [workflow_call]

jobs:
  cache-checkmate:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: cargo-checkmate

  run-phase:
    strategy:
      matrix:
        phase: [audit, build, check, clippy, doc, format, test]
    needs: cache-checkmate
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: cargo-checkmate
      - uses: actions/checkout@v3
      - run: cargo-checkmate ${{ matrix.phase }}
