name: cargo-checkmate phase

on:
  workflow_call:
    inputs:
      phase:
        type: string
        required: true
      checkmate-version:
        type: string
        default: "^0.1.14"

jobs:
  run-phase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-checkmate
          version: ${{ inputs.checkmate-version }}
      - run: cargo-checkmate ${{ inputs.run-phase }}
