name: cargo-checkmate phases

on:
  workflow_call:
    inputs:
      checkmate-version:
        type: string
        default: "^0.1.14"

jobs:
  checkmate-phases:
    strategy:
      matrix:
        phase: [audit, build, check, clippy, doc, format, test]
    steps:
      - uses: actions/checkout@v3
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-checkmate
          version: ${{ inputs.checkmate-version }}
      - run: cargo-checkmate ${{ matrix.phase }}
