name: cargo-checkmate phases

on:
  workflow_call:
    inputs:
      checkmate-version:
        type: string
        default: "^0.1.14"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-checkmate
          version: ${{ inputs.checkmate-version }}
      - run: cargo-checkmate audit

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-checkmate
          version: ${{ inputs.checkmate-version }}
      - run: cargo-checkmate build

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-checkmate
          version: ${{ inputs.checkmate-version }}
      - run: cargo-checkmate check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-checkmate
          version: ${{ inputs.checkmate-version }}
      - run: cargo-checkmate clippy

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-checkmate
          version: ${{ inputs.checkmate-version }}
      - run: cargo-checkmate doc

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-checkmate
          version: ${{ inputs.checkmate-version }}
      - run: cargo-checkmate format

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-checkmate
          version: ${{ inputs.checkmate-version }}
      - run: cargo-checkmate test

