on: [push]

name: cargo-checkmate Continuous Integration

jobs:
  cargo-checkmate:
    name: cargo-checkmate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cargo-checkmate/action@main
      - run: cargo checkmate check
      - run: cargo checkmate format
      - run: cargo checkmate clippy
      - run: cargo checkmate build
      - run: cargo checkmate test
      - run: cargo checkmate doc
      - run: cargo checkmate audit
