on: [push, pull_request]

name: cargo-checkmate Continuous Integration (build-checkmate)

jobs:
  cargo-checkmate-build-checkmate:
    name: cargo-checkmate-build-checkmate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-checkmate
      - run: cargo-checkmate clippy
      - run: cargo-checkmate build
