on: [push, pull_request]

name: Continuous integration

jobs:
  selftest:
    name: self-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo-checkmate
        run: cargo run
