on: [push]

name: cargo-checkmate Continuous Integration

jobs:
  cargo-checkmate:
    name: cargo-checkmate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo checkmate check
        uses: cargo-checkmate/action@main
        with:
          phase: check
      - name: cargo checkmate format
        uses: cargo-checkmate/action@main
        with:
          phase: format
      - name: cargo checkmate clippy
        uses: cargo-checkmate/action@main
        with:
          phase: clippy
      - name: cargo checkmate build
        uses: cargo-checkmate/action@main
        with:
          phase: build

      - run: pwd ; git status ; git rev-parse --git-dir ; git rev-parse --show-toplevel
      - run: git log --pretty='%Cred%h%Creset %C(yellow)%ai%Creset - %s <%C(bold blue)%ae%Creset>%Cgreen%d%Creset' --graph -10

      - name: cargo checkmate test
        uses: cargo-checkmate/action@main
        with:
          phase: test
      - name: cargo checkmate doc
        uses: cargo-checkmate/action@main
        with:
          phase: doc
      - name: cargo checkmate audit
        uses: cargo-checkmate/action@main
        with:
          phase: audit
