name: prototype cargo-checkmate action ci

on: pull_request

jobs:
  cargo-checkmate-image:
    name: cargo-checkmate-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo checkmate build
        uses: cargo-checkmate/action@use-checkmate-ghcr-image
        with:
          phase: check
      - name: cargo checkmate build
        uses: cargo-checkmate/action@use-checkmate-ghcr-image
        with:
          phase: format
      - name: cargo checkmate build
        uses: cargo-checkmate/action@use-checkmate-ghcr-image
        with:
          phase: clippy
      - name: cargo checkmate build
        uses: cargo-checkmate/action@use-checkmate-ghcr-image
        with:
          phase: build
      - name: cargo checkmate build
        uses: cargo-checkmate/action@use-checkmate-ghcr-image
        with:
          phase: test
      - name: cargo checkmate build
        uses: cargo-checkmate/action@use-checkmate-ghcr-image
        with:
          phase: doc
      - name: cargo checkmate build
        uses: cargo-checkmate/action@use-checkmate-ghcr-image
        with:
          phase: audit
