name: prototype cargo-checkmate action ci

on: pull_request

jobs:
  cargo-checkmate:
    name: cargo-checkmate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo checkmate clippy
        uses: cargo-checkmate/action@use-checkmate-ghcr-image
        with:
          phase: clippy
      - name: cargo checkmate build
        uses: cargo-checkmate/action@use-checkmate-ghcr-image
        with:
          phase: build
```
