on: [push]

name: cargo-checkmate Continuous Integration

jobs:
  cargo-checkmate:
    name: cargo-checkmate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cargo-checkmate/action@main
        with:
          phase: check
      - uses: cargo-checkmate/action@main
        with:
          phase: format
      - uses: cargo-checkmate/action@main
        with:
          phase: clippy
      - uses: cargo-checkmate/action@main
        with:
          phase: build
      - uses: cargo-checkmate/action@main
        with:
          phase: test
      - uses: cargo-checkmate/action@main
        with:
          phase: doc
      - uses: cargo-checkmate/action@main
        with:
          phase: audit
