name: cargo-checkmate Continuous Integration

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  phases:
    uses: ./.github/workflows/callee.yaml
    with:
      os-matrix: [ubuntu-latest, macos-latest]