on: pull_request

name: cargo-checkmate Continuous Integration (no-action parallel docker)

jobs:
  cargo-checkmate-no-action-parallel-docker
    name: cargo-checkmate-no-action-parallel-docker
    docker:
      - image: ghcr.io/cargo-checkmate/cargo-checkmate
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-checkmate
      - run: cargo-checkmate check
      - run: cargo-checkmate format
      - run: cargo-checkmate clippy
      - run: cargo-checkmate build
      - run: cargo-checkmate test
      - run: cargo-checkmate doc
      - run: cargo-checkmate audit

